apiVersion: v1 # api version
kind: Pod  # type of resource
metadata: # Dictionary
  name: myapp-pod # pod name
  labels: # Dictionary 
    app: myapp         
spec:
  containers: # List
    - name: myapp
      image: stacksimplify/kubenginx:1.0.0 # docker image
      ports: # container port
        - containerPort: 80